apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: product-service-2
  name: product-service-2
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: product-service-2
status:
  loadBalancer: {}